server:
  port: 9000

spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:postgresql://localhost:5433/cardsdb
    username: "postgres"
    password: "0000"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    sql:
      init:
        mode: always
    properties:
      hibernate:
        format_sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
management:
  endpoints:
    web:
      exposure:
        include: "*"