services:
  accounts:
    image: "rajpratik/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - rajpratik
  loans:
    image: "rajpratik/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - rajpratik


  cards:
    image: "rajpratik/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - rajpratik
networks:
  rajpratik:
    driver: "bridge"