server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:postgresql://localhost:5434/loansdb
    username: "postgres"
    password: "0000"
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    sql:
      init:
        mode: always
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
  config:
    import: "optional:configserver:http://localhost:8071/"
management:
  endpoints:
    web:
      exposure:
        include: "*"