services:
  accountsdb:
    image: postgres
    container_name: accountsdb
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: accountsdb               # Name of the default database
    extends:
      file: common-config.yml
      service: microservice-db-config


  cardsdb:
    container_name: cardsdb
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: cardsdb               # Name of the default database
    extends:
      file: common-config.yml
      service: microservice-db-config


  loansdb:
    container_name: loansdb
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: loansdb               # Name of the default database
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "rajpratik/configserver:s8"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8071/actuator/health" ]
      interval: 30s
      timeout: 30s
      retries: 10

    extends:
      file: common-config.yml
      service: microservice-base-config



  accounts:
    image: "rajpratik/accounts:s8"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: jdbc:postgresql://accountsdb:5432/accountsdb

    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "rajpratik/loans:s8"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: jdbc:postgresql://loansdb:5432/loansdb
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "rajpratik/cards:s8"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: jdbc:postgresql://cardsdb:5432/cardsdb
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  rajpratik:
    driver: "bridge"