spring:
  application:
    name: "configserver"
  profiles:
     active: git #native we use if we have to read config from local
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/sin-wave/IKB-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#         native:
#           search-locations: "file:///D://CODE//SpringBoot//configserver"

management:
  endpoint:
    web:
      exposure:
        include: "*"
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"


server:
  port: 8071