services:
  network-deploy-service:
    networks:
      - rajpratik


  microservice-db-config:
    extends:
      service: network-deploy-service
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_USER: "postgres"             # Username for the default user
      POSTGRES_PASSWORD: "0000"         # Password of the database



  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_DATA_SOURCE_USERNAME: "postgres"
      SPRING_DATA_SOURCE_PASSWORD: "0000"